### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [ArduinoMax/TLC5615#3]
Hi @ArduinoMax

we have detected that you changed the name of the library in `library.properties` from
  `TLC5615`
to
  `ArduMax TLC5615 Driver`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `ArduMax TLC5615 Driver`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 590 - 2018/01/15 15:43:14 Scraping https://github.com/ArduinoMax/TLC5615.git
JOB 590 - 2018/01/15 15:43:15 Checking out tag: v1.2.0
JOB 590 - 2018/01/15 15:43:15 Release TLC5615:1.2.0 already loaded, skipping
JOB 590 - 2018/01/15 15:43:15 Checking out tag: v1.2.1
JOB 590 - 2018/01/15 15:43:15 Release ArduMax TLC5615 Driver:1.2.1 has wrong library name, should be TLC5615
JOB 590 - 2018/01/15 15:43:15 Checking out tag: v1.2.2
JOB 590 - 2018/01/15 15:43:15 Release ArduMax TLC5615 Driver:1.2.2 has wrong library name, should be TLC5615
JOB 590 - 2018/01/15 15:43:15 Checking out tag: v1.3.0
JOB 590 - 2018/01/15 15:43:15 Release ArduMax TLC5615 Driver:1.3.0 has wrong library name, should be TLC5615
```

**Comment by xcvista** [comment]
Go ahead and rename it.
